# Copyright © 2022 Durudex

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

name: Linter

on:
  push:
    branches:
      - '**'
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - '**'
      - 'main'
      - 'dev'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v0.6.0

      - name: Lint Code
        uses: bufbuild/buf-lint-action@v1
